#!/usr/bin/env python3
"""Compare per-table row counts between SQLite and PostgreSQL."""

from __future__ import annotations

import argparse
import json
import sqlite3

import psycopg
from psycopg.rows import dict_row


def quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def sqlite_tables(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    return [row[0] for row in rows]


def sqlite_count(conn: sqlite3.Connection, table_name: str) -> int:
    row = conn.execute(f"SELECT COUNT(*) FROM {quote_ident(table_name)}").fetchone()
    return int(row[0])


def pg_count(conn: psycopg.Connection, table_name: str) -> int:
    with conn.cursor() as cur:
        cur.execute(f"SELECT COUNT(*) AS c FROM {quote_ident(table_name)}")
        row = cur.fetchone()
    return int(row["c"])


def pg_estimated_count(conn: psycopg.Connection, table_name: str) -> int:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT COALESCE(c.reltuples, 0)::BIGINT AS est
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = 'public'
              AND c.relkind = 'r'
              AND c.relname = %s
            """,
            (table_name,),
        )
        row = cur.fetchone()
    return int(row["est"]) if row else 0


def pg_tables(conn: psycopg.Connection) -> set[str]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT tablename
            FROM pg_catalog.pg_tables
            WHERE schemaname = 'public'
            """
        )
        rows = cur.fetchall()
    return {row["tablename"] for row in rows}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Verify SQLite vs PostgreSQL table row counts")
    parser.add_argument("--sqlite-path", required=True, help="Path to SQLite database file")
    parser.add_argument("--pg-dsn", required=True, help="PostgreSQL DSN")
    parser.add_argument(
        "--expected-counts-json",
        help="Optional JSON generated by migrate_sqlite_to_postgres.py --counts-json to avoid rescanning SQLite",
    )
    parser.add_argument(
        "--pg-count-mode",
        choices=("exact", "estimate"),
        default="exact",
        help="Use exact COUNT(*) or fast estimated pg_class.reltuples counts for PostgreSQL",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    sqlite_conn = sqlite3.connect(args.sqlite_path)
    pg_conn = psycopg.connect(args.pg_dsn, row_factory=dict_row)

    mismatches = 0
    try:
        expected_counts: dict[str, int] = {}
        if args.expected_counts_json:
            with open(args.expected_counts_json, "r", encoding="utf-8") as handle:
                payload = json.load(handle)
            expected_counts = {
                str(name): int(count) for name, count in (payload.get("row_counts") or {}).items()
            }
            tables = sorted(expected_counts.keys())
            print(f"sqlite_source=counts_json tables={len(tables)} path={args.expected_counts_json}")
        else:
            tables = sqlite_tables(sqlite_conn)
        pg_table_names = pg_tables(pg_conn)
        print(f"tables={len(tables)}")

        for table_name in tables:
            left = expected_counts.get(table_name)
            if left is None:
                left = sqlite_count(sqlite_conn, table_name)

            if table_name not in pg_table_names:
                print(f"MISSING table={table_name} sqlite={left} postgres=missing")
                mismatches += 1
                continue

            right = (
                pg_count(pg_conn, table_name)
                if args.pg_count_mode == "exact"
                else pg_estimated_count(pg_conn, table_name)
            )
            status = "OK" if left == right else "MISMATCH"
            suffix = "" if args.pg_count_mode == "exact" else " mode=estimate"
            print(f"{status} table={table_name} sqlite={left} postgres={right}{suffix}")
            if left != right:
                mismatches += 1

        print(f"mismatches={mismatches}")
        return 1 if mismatches else 0
    finally:
        pg_conn.close()
        sqlite_conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
